name: Jordi's Daily Commit

on:
  schedule:
    - cron: '*/30 8-17 * * 1-5'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main 

    - name: Create file and commit
      run: |
        FILE="commit_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Hello, my name is Jordi" > "$FILE"
          echo "commit number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
        fi
        git config --global user.name "joraman2"
        git config --global user.email "jordi@amorosandr.eu"
        git add "$FILE"
        git commit -m "Daily commit"
        git push https://x-access-token:${{ secrets.TOKEN }}@github.com/joraman2/DailyCommit.git
      env:
        TOKEN: ${{ secrets.TOKEN }}
